install -D app/src/main/res/mipmap-hdpi/app_launcher.png ci/app/src/main/res/mipmap-hdpi/app_launcher.png
install -D app/src/main/res/mipmap-hdpi/app_launcher_round.png ci/app/src/main/res/mipmap-hdpi/app_launcher_round.png
install -D app/src/main/res/mipmap-mdpi/app_launcher.png ci/app/src/main/res/mipmap-mdpi/app_launcher.png
install -D app/src/main/res/mipmap-mdpi/app_launcher_round.png ci/app/src/main/res/mipmap-mdpi/app_launcher_round.png
install -D app/src/main/res/mipmap-xhdpi/app_launcher.png ci/app/src/main/res/mipmap-xhdpi/app_launcher.png
install -D app/src/main/res/mipmap-xhdpi/app_launcher_round.png ci/app/src/main/res/mipmap-xhdpi/app_launcher_round.png
install -D app/src/main/res/mipmap-xxhdpi/app_launcher.png ci/app/src/main/res/mipmap-xxhdpi/app_launcher.png
install -D app/src/main/res/mipmap-xxhdpi/app_launcher_round.png ci/app/src/main/res/mipmap-xxhdpi/app_launcher_round.png
install -D app/src/main/res/mipmap-xxxhdpi/app_launcher.png ci/app/src/main/res/mipmap-xxxhdpi/app_launcher.png
install -D app/src/main/res/mipmap-xxxhdpi/app_launcher_round.png ci/app/src/main/res/mipmap-xxxhdpi/app_launcher_round.png